export type Product = { slug: string; name: string; size: string; resolution: string; brightness: string; interface: string; description: string; category: string; };
export const products: Product[] = [
 { slug:"23-inch-shelf-edge",name:"23.1-inch Shelf Edge Display",size:"23.1 in",resolution:"1920 × 158",brightness:"700 nits",interface:"HDMI / Android",description:"Example data: a slim retail shelf display for price, promotion and product information.",category:"Shelf Edge Displays" },
 { slug:"28-inch-stretched",name:"28.6-inch Stretched Bar LCD",size:"28.6 in",resolution:"1920 × 540",brightness:"500 nits",interface:"HDMI / LVDS",description:"Example data: a versatile bar type LCD display for digital signage projects.",category:"Stretched Bar LCD Displays" },
 { slug:"37-inch-ultra-wide",name:"37-inch Ultra-wide LCD Display",size:"37 in",resolution:"1920 × 540",brightness:"700 nits",interface:"HDMI / eDP",description:"Example data: a wide-format display for wayfinding and commercial advertising.",category:"Ultra-wide LCD Displays" },
 { slug:"43-inch-high-brightness",name:"43-inch High Brightness Bar Display",size:"43 in",resolution:"3840 × 720",brightness:"1000 nits",interface:"HDMI / Android",description:"Example data: a bright bar display concept for high-ambient-light environments.",category:"High Brightness Displays" },
 { slug:"32-inch-industrial",name:"32-inch Industrial Bar Display",size:"32 in",resolution:"1920 × 360",brightness:"500 nits",interface:"HDMI / LVDS",description:"Example data: a display configuration for equipment interfaces and process information.",category:"Industrial Bar Displays" },
 { slug:"21-inch-touch",name:"21.5-inch Touch Bar Display",size:"21.5 in",resolution:"1920 × 480",brightness:"450 nits",interface:"HDMI / USB Touch",description:"Example data: an interactive bar display for self-service and smart retail installations.",category:"Touch Bar Displays" }
];
export const blogPosts = [
 { slug:"what-is-a-stretched-bar-lcd-display",title:"What Is a Stretched Bar LCD Display?",description:"A practical introduction to the wide-format display category and how it is used in commercial projects.",body:"A stretched bar LCD display is a long, narrow display format designed for content where a conventional screen is too tall or too wide. Its proportions make it useful in shelf edges, transport information, menu boards and compact advertising locations.\n\nFor a project, screen size is only one part of the decision. Resolution, brightness, interface, enclosure and mounting all determine whether a bar type LCD display works in the intended environment. Starting with the installation space and viewing distance helps a display supplier recommend a sensible configuration." },
 { slug:"how-to-choose-a-shelf-edge-display",title:"How to Choose a Shelf Edge Display",description:"Key considerations for selecting a shelf edge display that fits retail operations and content needs.",body:"A shelf edge display needs to fit its retail fixture as well as its communication goal. Measure the available rail or shelf length, then consider the information customers need to see at a typical aisle viewing distance.\n\nBrightness, content management, power routing and mounting are important practical topics. For larger rollouts, prototype testing is valuable: it can confirm mechanical fit, legibility and the workflow for updating content before production quantities are planned." },
 { slug:"ultra-wide-lcd-smart-retail",title:"Applications of Ultra-wide LCD Displays in Smart Retail",description:"How ultra-wide LCD displays can support product information and targeted communication in smart retail.",body:"Ultra-wide LCD displays can give smart retail teams a flexible surface for pricing, promotion, wayfinding and product storytelling. A long display can sit where customers naturally look, including shelf edges and end caps.\n\nThe best use cases begin with a clear content plan. Retailers should define which messages are useful, how frequently they change and who maintains them. The display hardware can then be matched to the project’s brightness, connectivity and installation requirements." }
];
